# Generated by Django 3.1.3 on 2023-02-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pshs', '0004_apply_attendance_recurit'),
    ]

    operations = [
        migrations.CreateModel(
            name='assembly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='recurit',
            name='email',
            field=models.CharField(max_length=100),
        ),
    ]
