# Generated by Django 3.1.3 on 2023-02-03 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pshs', '0005_auto_20230202_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assembly',
            name='end_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assembly',
            name='start_time',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('assembly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pshs.assembly')),
            ],
        ),
    ]
