# Generated by Django 3.1.3 on 2023-02-03 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pshs', '0007_auto_20230203_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('clsss_num', models.IntegerField()),
                ('email', models.TextField()),
                ('recurit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pshs.recurit')),
            ],
        ),
    ]
