# Generated by Django 3.1.3 on 2023-02-03 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pshs', '0008_apply_recurit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
