# Generated by Django 3.1.3 on 2023-02-03 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pshs', '0009_delete_apply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('recurit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pshs.recurit')),
            ],
        ),
    ]
